CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    user_type VARCHAR(50) NOT NULL,
    email citext UNIQUE NOT NULL,
    username citext UNIQUE NOT NULL,
    display_name VARCHAR,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    phone_number VARCHAR,
    bio TEXT,
    password VARCHAR NOT NULL,
    status VARCHAR(50) NOT NULL,
    accept_policy boolean DEFAULT FALSE,
    receive_email boolean DEFAULT FALSE,
    email_verified boolean DEFAULT FALSE,
    profile_created boolean DEFAULT FALSE,
    preferred_language VARCHAR(10),
    profile_image_id BIGINT,
    profile_image_id_50 BIGINT,
    profile_image_id_100 BIGINT,
    profile_image_id_250 BIGINT,
    cover_image_id BIGINT,
    cover_image_id_250 BIGINT,
    cover_image_id_500 BIGINT,
    cover_image_id_800 BIGINT,
    cover_image_id_1200 BIGINT,
    secret citext NOT NULL,
    last_login TIMESTAMPTZ,
    last_get_passcode_time TIMESTAMPTZ,
    create_date TIMESTAMPTZ DEFAULT NOW(),
    update_date TIMESTAMPTZ
);
